### ISSUE TITLE
Non-eloquent resource creation results in a 200 HTTP code

### ISSUE THREAD

**Issue by robinstraub** [laravel-json-api/laravel#101]
I am using some non-eloquent resources in my project. 
When I POST new resouirces I get 200 codes instead of 201.
I did register a repository, implemented the `CreatesResource` contract and write a `create()` method implementation in my `CrudResource`.

Did I miss something ? Do you need a reproduction example ?

**Comment by lindyhopchris** [comment]
Hi! No you haven't missed anything. At the moment the response classes detect whether the underlying model/non-Eloquent object was created during the current HTTP request. For non-Eloquent objects this means you need to implement this interface on the class: https://github.com/laravel-json-api/core/blob/develop/src/Contracts/Resources/Creatable.php

If you don't want to implement the interface, you'd need to use the `created` hook on the controller to return a `DataResponse` that calls the `didCreate()` helper method as per these docs: https://laraveljsonapi.io/docs/1.0/responses/#create-resource-response

That'll work for the current release. I think though I should update the create controller action so that it always calls `didCreate` as that would make sense for that controller action. I'll leave this issue open to remind me to make that change.

**Comment by robinstraub** [comment]
Ok perfect, thanks for the wuick reply. I'll implement the interface in the meantime.
