### ISSUE TITLE
Meta count incorrect value when filtered results

### ISSUE THREAD

**Issue by bbprojectnet** [laravel-json-api/laravel#107]
Not sure is that a bug or maybe intended, but when results are filtered, meta count still show unfiltered value, for example:

```
	"meta": {
		"count": 2
	},
	"jsonapi": {
		"version": "1.0"
	},
	"data": [],
```

**Comment by lindyhopchris** [comment]
Yeah that's giving you the total of the relationship unfiltered. So you know that you've got `0/2` results.

**Comment by lindyhopchris** [comment]
This is part of the countable relations feature, that I currently deem as experimental... it's not going to make it into the `1.0.0-rc.1` release because I've got a number of issues with it that mean it's not production ready.

So I'm likely to disable it for `1.0.0` and sort it out for the `2.0.0` release (whenever that might be).

So for the moment I'd suggest you ignore it, safe in the knowledge it won't be active when I tag `1.0`.

**Comment by bbprojectnet** [comment]
Ok :) Thanks a lot.

**Comment by lindyhopchris** [comment]
Actually going to leave this issue open so I know to sort it out for the `1.0` release. Thanks for raising it as it's a good illustration of why I need to disable the experimental feature!

**Comment by lindyhopchris** [comment]
Closing this as the countable relationships feature is now off by default.
