### ISSUE TITLE
[Question] How to get relationship in controller hook?

### ISSUE THREAD

**Issue by bbprojectnet** [laravel-json-api/laravel#108]
Hi,

Is there more elegant way to get relationship model in creating controller hook than:

```
$foo = Foo::make()->resolveRouteBinding($fooRequest->input('data.relationships.foo.data.id'));
```

**Comment by bbprojectnet** [comment]
Related question, more elegant way to get json:api attributes than:

```
$fooRequest->input('data.attributes.foo');
```

in creating hook.

**Comment by lindyhopchris** [comment]
For the first one, you need to type-hint the `LaravelJsonApi\Contracts\Store\Store` interface. Then you can do:

```php
$post = $store->find('posts', $request->json('data.relationships.post.data.id'));
```

Or in answer to the second question, you could use the validated data to access the value you want. I.e.:

```php
$post = $store->find('posts', $request->validated()['post']['id']);
$foo = $request->validated()['foo']
```

This works because the validated data is a simpler structure - as it works on the concept that fields are collectively the attributes and relationships of a resource.

**Comment by bbprojectnet** [comment]
Thank you, works like a charm :)
