### ISSUE TITLE
question: does this package only work with models?

### ISSUE THREAD

**Issue by michabbb** [laravel-json-api/laravel#154]
hi,
i digged around and everything I see is connected to a model.
so I have to ask: what, if I want to return something that has nothing to do with a model ?
lets say I want to return the result of s super complex SQL query?
how do I do this or is that package "only" working with models?
thanks for any help!

**Comment by lindyhopchris** [comment]
https://laraveljsonapi.io/docs/1.0/digging-deeper/non-eloquent.html

**Comment by lindyhopchris** [comment]
FYI if you were going to use a raw SQL query, you will need to map each row to a specific object class. That's because all the detection around how to convert an object to a JSON:API resource is based on the fully-qualified class name of the object. But apart from that, if you follow the instructions in that chapter, you should be able to get it working.

**Comment by handita** [comment]
@lindyhopchris Helo chris can you give me an example of the implementation using custom query from database? I tried to google but no result. I'm confusing right now to make custom query to my model using non eloquent. I used this for aggregation data report. Thanks
