### ISSUE TITLE
[BUG] Laravel Validation Rule `prohibited` Not Working for Patch Requests

### ISSUE THREAD

**Issue by ISaidHey** [laravel-json-api/laravel#203]
Scenario:
Trying to patch a resource incorrectly fails if using the `prohibited` rule when correctly **not** providing the prohibited attribute in the request body.

The [Prohibited](https://laravel.com/docs/9.x/validation#rule-prohibited) rule for Laravel doesn't work due to [line ~234 in this package's ResourceRequest](https://github.com/laravel-json-api/laravel/blob/develop/src/Http/Requests/ResourceRequest.php#L233).  

When attempting a PATCH request, this section of code combines the http request body with the existing model data before validation. This causes a false negative to occur as the model may provide the field value when the request body doesn't. 

Validation should only validate the payload not the existing model's data.

Given:
- Rules
  ```
  class PictureRequest extends \LaravelJsonApi\Laravel\Http\Requests\ResourceRequest
  {
      /**
       * Get the validation rules for the resource.
       *
       * @return array
       */
      public function rules(): array
      {
          return [
              'isArchived' => ['required', 'boolean'],
              'name' => ['prohibited'],
          ];
      }
  }
  ```
- Payload
  ```
  {
    "data": 
      {
        "id": "1",
        "type": "pictures",
        "attributes": {
          "isArchived": true
        }
        
      }
  }
  ```

Response:
```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "The name field is prohibited.",
            "source": {
                "pointer": "/data/attributes/name"
            },
            "status": "422",
            "title": "Unprocessable Entity"
        }
    ]
}
```

**Comment by BenWalters** [comment]
@ISaidHey I just tested this as I recently implemented prohibited validation rules on an endpoint and can also confirm the same behaviour. And it is documented that it will work this way:
> If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.
https://laraveljsonapi.io/docs/2.0/requests/resources.html#updating-resources

I agree it conflicts and causes a problem with that Laravel validation rule.
@lindyhopchris do you have any suggestions about how best to handle this?

**Comment by lindyhopchris** [comment]
Yes this isn't a bug - as @BenWalters has commented, the JSON:API spec specifies that the server must interpret missing values as the existing values. We therefore do that merging so that validation is straightforward, particularly for rules that depend on multiple attributes e.g. `required_with` as it would be a nightmare trying to deal with those scenarios if you had to work out whether or not the client had provided a value and if not what the current value was.

Your scenario is easily handled because we already provide the ability to modify the merging. All you need to do is unset the value from the existing values, using the `withExisting()` method on your resource request class, as documented here: https://laraveljsonapi.io/docs/2.0/requests/resources.html#customising-existing-values

The example in that section of the docs shows unsetting an existing value, which is what you need to do for your `name` attribute. I.e.:

```php
class PictureRequest extends ResourceRequest
{
    // ...

    /**
     * Modify the existing resource before it is merged with client values.
     *
     * @param Picture $model
     * @return array|null
     */
    protected function withExisting(Picture $model, array $resource): ?array
    {
        unset($resource['attributes']['name']);

        return $resource;
    }
}
```

**Comment by BenWalters** [comment]
@lindyhopchris Thanks for the input. Although, I'm not sure this fully resolves the issue, I'll expand:

Our endpoint allows only certain fields to be edited based on the user role, therefore if they aren't permitted to change a field the validation rule is set as prohibited. I.e. cannot always be unset. Granted, it's likely possible to duplicate the logic that's used to apply the validation rule to conditionally unset it. 
However, that brings me to the following issue - if you always unset it where the user is 'prohibited' from updating that field they won't get a validation error... only the field won't be updated (the validation rule will never fail).

**Comment by lindyhopchris** [comment]
So the `prohibited` rule means the field must be "empty or not present" according to the Laravel docs.

The problem raised by this issue is that if the client doesn't provide a value for a prohibited attribute, the merging of existing attributes means that there is actually a value (the existing value) even if the client hasn't provided one - so the rule then fails.

The solution above unsets the _existing_ value from the existing values _before_ they are merged with the client values. Therefore, if you unset the existing value for the prohibited field, and the client hasn't provided a value for the prohibited field, then the rule will pass. If the client has provided a value, the rule will fail.

So the solution here does work for the prohibited field. I'm not sure I totally follow what your use case is @BenWalters and why the solution doesn't work for it, but if the solution doesn't work then I think you're indicating there's some other problem?

**Comment by BenWalters** [comment]
@lindyhopchris You're completely correct! I had understood the `withExisting` function to be working differently to how it is. 
I can confirm that using the `withExisting` hook resolves the issue. Thanks.

**Comment by lindyhopchris** [comment]
@BenWalters great, no problem - glad to hear it's working!

**Comment by ISaidHey** [comment]
Coming back to this issue because I thoroughly enjoy this package, have used it in many projects, have used this workaround, and I still think this is a mistake. 

I understand the JSON:API rule and don't take issue with it but rather the fact that a FormRequest is validating more than the payload being sent by the client. It's a mixture of responsibilities.  When the `prohibited` rule is used, it is to indicate to the client that you cannot in any way send that attribute. The validator should only be validating the payload not the payload merged with the current state. Validator validates the payload first, then merge with existing data, then apply JSON:API rules and regulations.
