### ISSUE TITLE
Caching support for get requests

### ISSUE THREAD

**Issue by darakanoit** [laravel-json-api/laravel#207]
Are there any implementation options for caching get requests? 
I've seen a package from [spatie](https://github.com/spatie/laravel-responsecache), but I'm not sure if it fits me. My path is /employee/{employee}/items, but the party says that the cache works for every user, but I don't have users, but employees.

**Comment by lindyhopchris** [comment]
Caching is not covered by the Laravel JSON:API package, because caching is not something defined by the JSON:API spec. Using a Laravel package that specifically deals with caching would be the solution. I can't really advise which package to use or how a specific caching package works. Spatie are a good choice for packages as their packages are normally really good. If you have questions about their caching package, you'll need to ask them.
