### ISSUE TITLE
Missing Exception Renderer for MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by martianatwork** [laravel-json-api/laravel#21]

**Comment by lindyhopchris** [comment]
`Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException` is already handled by the exception parser, because it implements the `HttpExceptionInterface`.

Can you double check the exception class to make sure you've reported the correct one? Plus if you are getting an exception that is not rendered - what's triggering the exception?

**Comment by lindyhopchris** [comment]
I'm closing this because I think you mean the `Symfony\Component\Routing\Exception\MethodNotAllowedException` - which isn't encountered in normal Laravel request/response handling.

The `Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException` is already handled by the exception parser, because it implements the `HttpExceptionInterface`. I added this test to ensure that it was covered:
https://github.com/laravel-json-api/exceptions/commit/fd6c2e09b19537d0abd66efc154bf4748060bec6
