### ISSUE TITLE
How to get data for events

### ISSUE THREAD

**Issue by genyded** [laravel-json-api/laravel#239]
We're making good progress with JSONAPI, but now events are tripping us up. We followed the guidelines at https://laraveljsonapi.io/docs/3.0/servers/events.html#resource-events and created an Observer for the User model. We then put into it:

```php
<?php

namespace App\Observers;

use App\Models\User;

class UserObserver
{
    /**
     * Handle the User "created" event.
     */
    public function created(User $user): void
    {
        dd($user);
    }
}
```

The event triggers when we create a user via JSON API, but the user is empty. How can we get the user data in the event?

**Comment by BenWalters** [comment]
That's strange! I don't think that'll be directly related to this package as the observer is core laravel functionality.
 
I assume you aren't doing anything specific to trigger the event and that you're letting laravel do that for you?
Is the `dd($user)` actually getting hit? Or is it returning `null`?

**Comment by genyded** [comment]
We're creating the user via the standard JSON API end point and because of the Observer, the event auto fires, but the user in the event is an empty object (not null).

If we create via standard Laravel model and not JSON API it all works as expected. Pretty sure it's becuse the user is JSON using the API and Laravel is expecting a model.

**Comment by lindyhopchris** [comment]
So using observers in this way works in my production apps, so I'm not sure what's going on here.

When you say the user in the event is an empty object, presumably it is of type `User`? Because otherwise you'd get a type error when the method is called as the argument is type-hinted.

What I'd do is throw an exception from the `created` method on the observer and see what the stack trace is - so you can pin down what in the code is causing Laravel to fire the created event.

**Comment by genyded** [comment]
OK, we figured this out (we think). It looks like the issue was related to some of the packages not being properly loaded in the Docker containers. We're still not sure exactly why this happened and may never know. 

Anyway, after bringing everything back up in Docker, it's all working as expected now. Closing this since it's resolved. Thanks for the super fast responses yet again!
