### ISSUE TITLE
Question: how do I create a simple endpoint /login?

### ISSUE THREAD

**Issue by juliorafaelr** [laravel-json-api/laravel#256]
Let's say I want to create a simple endpoint `login` that's not an action attached to a model, and I want to create a simple logic on it. How can I make this happen?

**Comment by lindyhopchris** [comment]
You can just create an endpoint in exactly the way you would when using Laravel - i.e. register a route, write a controller. 

If you want to return a JSON:API response from the controller, you can use one of the package's response classes:
https://laraveljsonapi.io/docs/3.0/responses/

**Comment by lindyhopchris** [comment]
Hi! yeah, that's fair feedback. In response, I'd say that I find it really stressful having lots of open issues. So that's why I close things that realistically (factoring in everything else I need to do on the package) I'm not going to have time to do anything with.

If you'd like to submit a PR to the docs adding something for this scenario, that would be appreciated.
