### ISSUE TITLE
Incorrect data serialization within ArrayHash (Hashable trait)

### ISSUE THREAD

**Issue by rapkis** [laravel-json-api/laravel#273]
First of all, I'm very thankful that this package exists. I'm using it to develop an API and have run into a problem related to JSON data serialization. When using the `ArrayHash` field within a schema, it appears to be incorrectly serializing empty arrays - it returns them as `null`. Which is a different behavior, compared to an `ArrayList`. To keep it simple, let's take an example:

Imagine there's a table with a non-nullable array/json column.
If I were to serialize the column's value `{'foo': 'bar'}`, the result would still be `{'foo': 'bar'}`. But if I were to serialize an empty array like `[]`, then serializing it would return `null`. This doesn't properly reflect the structure of the data and can be misleading.
(on the other hand, serializing values `['foo', 'bar']` and `[]` within an `ArrayList` would still return both of the original values)

It appears to be caused by the usage of `\LaravelJsonApi\Core\Json\Hash` within `ArrayHash`'s `serialize()` method. The `Hash` class uses the `Hashable` trait's `jsonSerialize()` method, which always returns `null` for an empty value.

My suggestion is to always return the original value within `\LaravelJsonApi\Core\Json\Concerns\Hashable`->`jsonSerialize()`, even when that value is empty.

I don't want to make any assumptions since I'm new to this repository and I haven't found any issues or PRs related to this. Perhaps the current behavior is intended? If not, I'd be willing to open a PR for this.

**Comment by lindyhopchris** [comment]
Hey! Glad you're finding the package useful.

This is intentional. Here's why...

In JSON, a PHP array hash is an object. Therefore, an empty array needs to be serialised to `null` in JSON. Because otherwise, clients would have to handle in Javascript the value being either an object or an array. It makes more sense for the client to expect an object or `null`.

For an array list, in JSON/Javascript that's an array. Therefore an empty PHP array list can be serialised to an empty array.

Hope that makes sense!
