### ISSUE TITLE
Inability to use dependency injection in the server class

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#37]
The server class is currently constructed in `\LaravelJsonApi\Core\Server\ServerRepository` like this:

```php
$server = new $class($this->container, $name);
```

I like to always use DI instead of facades and global helpers but that is not possible at the moment because of this line (for example when adding a scope that needs some dependency in the `serving` method of the server).
My suggestion would be to have the server bound in the container under a convention key, like `jsonapi_server_{$name}`.

So the line from above would become

```php
$server = $this->container->make("jsonapi_server_{$name}");
```

That way we could completely override the binding in our code (or just contextually bind a dependency, like a guard for example if needed).

What do you think?

**Comment by lindyhopchris** [comment]
I'd take a PR to the `laravel-json-api/core` repo, that changes that line to:

```php
$server = $this->container->make($class, [
    'container' => $this->container,
    'name' => $name,
]);
```

I prefer that to `$server = $this->container->make("jsonapi_server_{$name}");` because for that to work, I'd need to iterate over the config to bind things into the service container, which would happen on every request even though a request is only going to relate to a single server.

**Comment by X-Coder264** [comment]
Great, I'll send that PR sometime in the next 24 hours (as soon as I get a bit of free time).

**Comment by X-Coder264** [comment]
PR sent -> https://github.com/laravel-json-api/core/pull/3
