### ISSUE TITLE
Availability to hash ids

### ISSUE THREAD

**Issue by juljupy** [laravel-json-api/laravel#41]
Hey congrats for your work, it's great.

I'm wondering if theres a way to show hashed (e.g. with https://github.com/vinkla/laravel-hashids) when sending response to the client.

<img width="413" alt="Screen Shot 2021-02-25 at 12 06 28 PM" src="https://user-images.githubusercontent.com/867837/109189512-15badc00-7762-11eb-9ee7-385886928320.png">

Thanks for your ideas.

**Comment by lindyhopchris** [comment]
So encoding it would be relatively simple as it just comes from the `JsonApiResource` classes `id()` method.

The problem is then the client is going to send the ids back to the server hashed. Which means wherever this package encounters an id, it would have to decode it before using it (e.g. to query the database).

That's something I'm prepared to wire in, as it would be a good addition. But it'll take me a little while to figure out everywhere I need to wire it in.

**Comment by juljupy** [comment]
Hi @lindyhopchris thanks for you response.

I didn't realize the `id()` method.  Thanks for point it out, for the case when the user sends back the hashed id I think I could write a middleware that decodes the id before request gets processed.  That's could be an option, but I'll keep searching for a solution.

**Comment by lindyhopchris** [comment]
I'm going to re-open this, because I'd like to implement this. Think it'd be great functionality to have - just not totally sure when I'll get to it.

**Comment by juljupy** [comment]
Oh great, I'll be awaiting for this feature.

**Comment by lindyhopchris** [comment]
@juljupy just want to double check - your intent is to encode one Eloquent model id using hashids? I notice the library returns an array when decoded, but I'm assuming I can code for that to expect a single model id in the decoded array?

**Comment by juljupy** [comment]
Hi @lindyhopchris, yes it is to encode on Eloquent model.

**Comment by lindyhopchris** [comment]
Thanks for opening this issue - it's a really great addition to the package, so I'm glad to have implemented it!

It'll be in the `1.0.0-beta.1` release. Not sure exactly when I'll be tagging that, but should be some point in the next week or two.

The documentation on this feature is here:
https://github.com/laravel-json-api/docs/blob/develop/1.0/schemas/identifier.md#hash-ids

**Comment by Mina-R-Meshriky** [comment]
hey, that is very interesting.
I am much interested in the **Custom ID Encoding**. but I need to access the model being encoded as well, so to create a different encoding for each model
problem e.g.: **_Post_** with id: 1  -> encoded : alksj34  ||  _**User**_ with id: 1  -> encoded : alksj34 
what I want:  **_Post_** with id: 1  -> encoded : alksj34  ||  _**User**_ with id: 1  -> encoded : cdsbh938 
```php
public function encode($modelKey): string {
        // how can I get the model here ?
    }
```

**Comment by lindyhopchris** [comment]
@Mina-R-Meshriky having access to the model when encoding/decoding makes no sense, because it wouldn't be possible to have access to the model when decoding the resource id - as the resource id needs to be decoded so that the model can be retrieved.

What exactly is the use case? Why do you need access to the model?

If you have different encoding approaches for the `id` for a `Post` and `User` model, then the way you would implement this is to have a `PostId` field and a `UserId` field. Both implement the `IdEncoder` contract as per the docs, but you would then know which id you are encoding/decoding.

**Comment by lindyhopchris** [comment]
@Mina-R-Meshriky just to follow up...

In the `HashId` implementation, this is possible by e.g. on the `PostSchema` calling `HashId::make()->useConnection('posts')` and on the `UserSchema` calling `HashId::make()->useConnection('users')`.

You could implement something yourself - i.e. have your own custom `id` field that has a method on which you tell it what type of id (e.g. posts or users) it is encoding. See the `HashId` implementation here:
https://github.com/laravel-json-api/hashids/blob/develop/src/HashId.php

**Comment by Mina-R-Meshriky** [comment]
ok actually I completely misrepresented what I need, what I need is just the name/type of model being encoded/decoded -> user or post
and you are completely right, I can do it as a fluent setter in the custom class

**Comment by lindyhopchris** [comment]
@Mina-R-Meshriky great, glad that works for you!
