### ISSUE TITLE
Filtering by many to many relation throws an exception

### ISSUE THREAD

**Issue by heyiammushu** [laravel-json-api/laravel#49]
Trying to implement filtering resource by its relationship column, but it throws an exception ```Expecting pivot filter to be used with a belongs-to-many relation. {"userId":1,"exception":"[object] (LogicException(code: 0): Expecting pivot filter to be used with a belongs-to-many relation. at /var/www/html/vendor/laravel-json-api/eloquent/src/Filters/WherePivotIn.php:40)```. Have two resources: workers and dayoffs, many to many relation between them, defining filtering like here https://laraveljsonapi.io/docs/1.0/schemas/filters.html#wherepivotin.
##### DayOffs schema
```
public function fields(): array
    {
        return [
            ID::make(),

            DateTime::make('day'),
            BelongsToMany::make('workers'),

            DateTime::make('createdAt')->sortable()->readOnly(),
            DateTime::make('updatedAt')->sortable()->readOnly(),
        ];
    }

    public function filters(): array
    {
        return [
            WhereIn::make('id', $this->idColumn()),
            WherePivotIn::make('workers', 'worker_id')
        ];
    }
```
Did I miss something?

**Comment by lindyhopchris** [comment]
Might be a bug. Can you just confirm what the `workers` relationship is on the `DaysOff` model?

**Comment by heyiammushu** [comment]
##### DayOff model
```
public function workers()
{
    return $this->belongsToMany(Worker::class, 'worker_day_off')->withTimestamps();
}
```

**Comment by lindyhopchris** [comment]
Have looked into this. The bug is in your code... the `WherePivot`, `WherePivotIn` and `WherePivotNotIn` methods can only be used when *querying a belongs to many relationship*. I.e. they cannot be used in the schema's `filter()` method - they have to be used in the relationship like this:

```php
BelongsToMany::make('workers')->withFilters(
    WherePivotIn::make('workers', 'worker_id')
);
```

The technical reason for this is because the Laravel methods they call - `wherePivot`, `wherePivotIn` and `wherePivotNotIn` - can only be called on the relationship, as shown here:
https://laravel.com/docs/8.x/eloquent-relationships#filtering-queries-via-intermediate-table-columns

I'll update the Laravel JSON:API docs to make this a bit clearer.
