### ISSUE TITLE
Unsupported Media Type - without sending media

### ISSUE THREAD

**Issue by kraionz** [laravel-json-api/laravel#91]
Hi, 

When creating a resource I get the following error, without sending media

Url: '/api/v1/products',

```
detail: "The request entity has a media type which the server or resource does not support."
status: "415"
title: "Unsupported Media Type"
```

Code Vuejs axios: 

```
const options = {
    headers: {
        "content-type": "application/json",
        "Accept": "application/json"
    }
}

axios.post('/api/v1/products', { name: 'Prueba' }, options)
    .then(function (response) {
      console.log(response);
})
```

Thanks in advance

**Comment by lindyhopchris** [comment]
Hi! The answer is in the code you've provided. You're using `application/json` which is an invalid media type for JSON:API. You need to use `application/vnd.api+json`.

**Comment by kraionz** [comment]
Hi @lindyhopchris, thanks for your reply

If I tried `application/vnd.api+json`, I wanted to cover one error at a time

when putting these headers it throws me another error
```
detail: "The member data is required."
source: {pointer: "/"}
status: "400"
title: "Non-Compliant JSON:API Document"
```

Code Vuejs axios:

```
const options = {
    headers: {
         "content-type": "application/vnd.api+json",
          "Accept": "application/vnd.api+json"
    }
}
axios.post('/api/v1/products', { name: 'Prueba' }, options)
    .then(function (response) {
      console.log(response);
})
```

**Comment by kraionz** [comment]
Sorry I'm a little newbie to json: api, I do my research and think that caused the error

The way you send the data must have a certain structure, you can correct me

```
axios.post('/api/v1/products', {
                data: {
                    type: 'products',
                    "attributes": {
                        name: 'Prueba'
                    }
                }}, options)
                .then(function (response) {
                console.log(response);
            })
```

**Comment by lindyhopchris** [comment]
The error message is telling you what the problem is: "The member data is required." I.e. the top-level data member is missing. You are right that it must have a certain structure - the structure is defined in the JSON:API specification. There's examples for creating a resource here:
https://jsonapi.org/format/#crud-creating

I suggest you read the specification before trying to use it!!

Really these issues are for bug reports. If you've got questions, there's a #questions channel in our Slack workspace. Link to Slack is on [our website](https://laraveljsonapi.io)
